### ISSUE TITLE
老哥有扣扣吗，有个问题想请教下你啊

### ISSUE THREAD

**Issue by ZhangMingZhao1** [ZJH9Rondo/Blog-Node#1]
求老哥联系方式

**Comment by ZJH9Rondo** [comment]
@ZhangMingZhao1 这样吧，点赞这个我这两天把那个功能的实现写个wiki，到时候艾特你，有问题的话在这下面回复，我会及时回复的，相关问题加了联系方式几句话说不清楚，抱歉啊

**Comment by ZhangMingZhao1** [comment]
好的，点赞和github登入这两个功能都写一下wiki，谢谢了，大佬 =0-0=

**Comment by ZJH9Rondo** [comment]
@ZhangMingZhao1 关于github第三方登录的我写了，[链接](https://github.com/ZJH9Rondo/Blog-Node/wiki/Github%E7%AC%AC%E4%B8%89%E6%96%B9%E8%AE%A4%E8%AF%81%E7%99%BB%E5%BD%95%E5%AE%9E%E7%8E%B0)

**Comment by ZhangMingZhao1** [comment]
好的

**Comment by ZJH9Rondo** [comment]
@ZhangMingZhao1 简单写了下，你看看，望指正 [链接](https://github.com/ZJH9Rondo/Blog-Node/wiki/%E7%94%A8%E6%88%B7%E6%96%87%E7%AB%A0%E7%82%B9%E8%B5%9E%E5%8A%9F%E8%83%BD%E5%AE%9E%E7%8E%B0)
